direction: right
vars: {
  d2-config: {
    pad: 50
    theme-overrides: {
      N1: "#001324"
      N2: "#192A39"
      N4: "#4C5965"
      N5: "#7F8991"
      N7: "#E5E7E9"
      B1: "#2D2DF1"
      B2: "#4444ED"
      B3: "#6C6CF1"
      B4: "#9595F5"
      B5: "#BFBFF9"
      B6: "#E9E9FD"
      AA4: "#FF7F48"
      AA5: "#FF7F48"
      AB4: "#FF7F48"
      AB5: "#FF7F48"
    }
  }
}

classes: {
  tealBox: {
    style: {
      fill: "#17CAC6"
      stroke-width: 0
    }
  }
}
leftBlockchain: {
  near: center-left
  shape: rectangle
  label: "Algorand Blockchain"
  account1: {
    shape: rectangle
    label: "Account 1\nBalance: 500000000\nStatus: Online"
    address: {
      height: 50
      label: "Address: 57O3WBBRJAXXEMAT..."
    }
    address.class: tealBox
  }
}
algorandAddress: Algorand Address {
  near: bottom-left
  style: {
    fill: transparent
    stroke-width: 0
  }
  address: {
    height: 50
    label: "57O3WBBRJAXXEMAT..."
  }
  address.class: tealBox
}
transaction: Transaction {
  shape: page
  label.near: top-center
  from: {
    height: 50
    label: "From: PLDQ57..."
  }
  to: {
    height: 50
    label: "To: 57O3WB..."
  }
  amount: {
    height: 50
    label: "Amount: 100000000"
  }
  fee: {
    height: 50
    label: "Fee: 1000"
  }
}
rightBlockchain: {
  grid-columns: 1
  near: center-right
  shape: rectangle
  label: "Algorand Blockchain"
  account1: {
    shape: rectangle
    label: "Account 1\nBalance: 399999000\nStatus: Online"
    address: {
      height: 50
      label: "Address: PLDQ57WWG7ECNUQ..."
    }
    address.class: tealBox
  }
  account2: {
    shape: rectangle
    label: "Account 2\nBalance: 100000000\nStatus: Offline"
    address: {
      height: 50
      label: "Address: 57O3WBBRJAXXEMAT..."
    }
    address.class: tealBox
  }
}
algorandAddress.address -> transaction.to: {
  style: {
    stroke-dash: 3
  }
}
transaction.to -> rightBlockchain.account2.address: {
  style: {
    stroke-dash: 3
  }
}
