direction: left
vars: {
  d2-config: {
    pad: 60
    layout-engine: tala
    sketch: true
    theme-overrides: {
      N1: "#001324"
      N2: "#192A39"
      N4: "#4C5965"
      N5: "#7F8991"
      N7: "#dfe1e5"
      B1: "#2D2DF1"
      B2: "#4444ED"
      B3: "#6C6CF1"
      B4: "#9595F5"
      B5: "#BFBFF9"
      B6: "#E9E9FD"
      AA4: "#FF7F48"
      AA5: "#FF7F48"
      AB4: "#FF7F48"
      AB5: "#FF7F48"
    }
  }
}
classes: {
  tealBox: {
    style: {
      fill: "#17CAC6"
      stroke-width: 0
    }
  }
  container: {
    label.near: top-center
    style: {
      stroke: "#192A39"
    }
  }
}
localStorage: Application Data Storage {
  "Global State, 0-64x": {
    shape: sql_table
    key: 1-64 bytes
    value: uint64 or 0-127 bytes
  }
  "Per-Account Local State, 0-16x": {
    shape: sql_table
    key: 1-64 bytes
    value: uint64 or 0-127 bytes
  }
  Boxes, 0-∞: {
    shape: sql_table
    key: 1-64 bytes
    value: 0-32,768 bytes
  }
}
localStorage.class: container
